### ISSUE TITLE
Proivde ability to set z_addr when there're multiple addresses on the node

### ISSUE THREAD

**Issue by asbachb** [ZencashOfficial/secnodetracker#11]
I've a node with two z_addr, the tracker selects the latest for doing the challenges. Might be useful to select the z_addr which should be used.

**Comment by ADumaine** [comment]
The tracker actually selects the first z-address found.
Will keep open as feature request.

**Comment by ADumaine** [comment]
tracker v0.1.0 now checks all available z-addresses for a balance and uses the first found.
