### ISSUE TITLE
Error: Node address ... is not a valid address 

### ISSUE THREAD

**Issue by goldflower** [ZencashOfficial/secnodetracker#14]
Hi devs:

When I execute "node app.js".

I bumped into this error:

"Node address znhkmE4eV22t9wdToM8Whyu67UveRicHGgF is not a valid address"

The interesting thing is, this address is different from my stake address which I provided.

I tried to use "node setup" and "vim ~/zencash/secnodetracker/config/stakeaddr", both didn't solve this issue.

**Comment by ADumaine** [comment]
Addresses staring with 'zn' are mainnet addresses.  The servers were still running on testnet.  Should resolve once servers are switched to mainnet.
