### ISSUE TITLE
Migration directions: serverurl doesn't exist 

### ISSUE THREAD

**Issue by fungic** [ZencashOfficial/secnodetracker#15]
Migration instructions say to remove `serverurl` but all I have on mine is `servers` . Are these the same (should I remove `servers` before git pull) ?

> Update secnodetracker
> Stop the tracker application.
> Delete the following files in the secnodetracker/config folder:
> nodeid, serverurl, lastChalBlock, lastExecSec, stakeaddr

**Comment by radiogena** [comment]
Why you don’t try remove ‘servers’ and let us know?

**Comment by ADumaine** [comment]
'serverurl' was for older versions.  The 'servers' file is currently used.  It should be recreated during setup if it does not exist.

**Comment by fungic** [comment]
Thank you.
