### ISSUE TITLE
Zend error: no auth mechanism defined

### ISSUE THREAD

**Issue by JulRider** [ZencashOfficial/secnodetracker#24]
I had this error when trying to use the tracker.

I figured that if rpcuser or rpcpassword in the zen.conf file contain a '#', it won't generate rpcuser and rpcpassword file in the config folder so will fail the authentication. 

It might be the case for other fields but I didn't try.

**Comment by ADumaine** [comment]
A line starting with # is a comment which means it is disabled.  The tracker ignores these lines by design.

**Comment by JulRider** [comment]
I know that.

The # wasn't in the begging of the line.

Just try that in the config file:
rpcuser=test#
rpcpassword=test#
rpcport=6666
rpcallowip=127.0.0.1

**Comment by ADumaine** [comment]
You are correct.  The setup looks for # on the line, not at the beginning of the line.
That can be changed for the next version.
For now a password or user can not have a # in it.

**Comment by ADumaine** [comment]
A # can now be used in versions 0.2.0 and above.
