### ISSUE TITLE
Duplicate node entry

### ISSUE THREAD

**Issue by nikmit** [ZencashOfficial/secnodetracker#26]
zenm.mitev.net is currently listed twice, with same IP and domain name. As much as a unique FQDN is a requirement, it looks like a bug.

**Comment by imanc** [comment]
My server znode.imancpro.it is listed three times!

**Comment by ADumaine** [comment]
This may happen if changes are made to the node or there are multiple reconnects.  The server takes a while to catch up on the home page, but there is still only one record in the database.

**Comment by nikmit** [comment]
When that does happen, which entry of the multiple listed is used for tracking uptime? If there is logic in place to pick any error-free copies over any (stale) other ones then I guess this is just a cosmetic issue.

**Comment by ADumaine** [comment]
The data on the home page comes directly from working memory.  Other pages are calls to the database.
The duplicates may show up on the home page and will clear but they do not affect tracking any downtime.

**Comment by nikmit** [comment]
Well I can't see duplicates in the list any more, even if I start a second copy of the tracker app on the node, so I guess the issue is fixed. It also seems it was only cosmetic, so closing.

**Comment by ADumaine** [comment]
There should never be a second instance of the tracker running on a node.
