### ISSUE TITLE
How to remove staking address from node?

### ISSUE THREAD

**Issue by infsafe** [ZencashOfficial/secnodetracker#28]
I created a  secnode, and it failed to make the challenge, so I ordered a new VPS to setup secnode, but the T-Address used for staking can't be used on my new VPS. How to remove it from the node?
Thanks!

**Comment by reppolice** [comment]
You changed companies? You shouldn't have to change anything if you transfer over your TLS, you created new TLS too?

**Comment by nikmit** [comment]
@insafe in your stakeaddr file enter a new staking address (with no balance on it) and restart tracker
the file is in <secnodetracker compile dir>/config/stakeaddr

have not tested but should work

**Comment by ondrejnov** [comment]
I have same problem. I need move staking address to another VPS. How can I remove old secure node? Change address to blank with no balance doesnt work. ("Could not change to new stake znAA . New balance is only 0")

**Comment by ADumaine** [comment]
Secure nodes are never deleted from the server.   

The stake address can be changed to a new address by using the technique nikmit described or by running 'node setup' and entering the new stake address.

ondrejnov: you have not indicated if the new node is a rebuild or a completely new node.
