### ISSUE TITLE
tracker not seeing stake balance correctly

### ISSUE THREAD

**Issue by rubenmozo** [ZencashOfficial/secnodetracker#29]
I moved my funds to another transparent address, changed in tracker setup and when started tracker says: Stake address below 42. Balance is 0

node: https://securenodes.eu.zensystem.io/nodes/391/detail
new stake adress:  https://explorer.zensystem.io/address/znmeucZJS79Xz1h6pG7w4biYdURZEBrZ1nu

I think it's an important bug.

**Comment by ADumaine** [comment]
It looks like the stake address was recognized.  It is a good idea to send and confirm the funds in the new address before changing it in the tracker.

**Comment by rubenmozo** [comment]
Hi @ADumaine , for your information, funds were confirmed. I had to change server location in tracker from EU to USA to tracker start seeing stake funds. When tracker recognized stake, I changed back to EU and all worked fine. I think there is something in server side or tracker not working fine.
