### ISSUE TITLE
Specify challenge address

### ISSUE THREAD

**Issue by Reeebuuk** [ZencashOfficial/secnodetracker#32]
I've cloned my linode image and wanted to spin it up on another VPS but the issue is that the challenge address stayed the same and I cannot change it?
Why isn't allowed to specify it during node setup?
Or any suggestions how to change it?

Error message:
`Registration failed. Node t_address already registered.`

And it is using the challenge address from first VPS which I cannot change? I have a list of them but how to change it in setup?

**Comment by sbacelic** [comment]
Just redownload secnodetracker

**Comment by Reeebuuk** [comment]
I did, have removed the whole folder and pulled again.
Have run fresh `node setup` and no previous values where there.

**Comment by ADumaine** [comment]
When cloning the wallet.dat should not be cloned or if it is, it should be removed  on the clone and a new one allowed to be created.   New private addresses should then be created in the new wallet and challenge funds sent to it.

The node uses the first transparent address in the wallet for the node identity.  There can not be two of the same.

**Comment by Reeebuuk** [comment]
That worked, have deleted wallet.dat and it worked. Thx!
