### ISSUE TITLE
Something new or blast from the past? zend "wobble"

### ISSUE THREAD

**Issue by reppolice** [ZencashOfficial/secnodetracker#33]
I was running at 100% for several days, and did not touch anything on this Azure oversized node. And suddenly, without actually any email alert,  no server load and most probably a completely fake downtime:
https://securenodes.eu.zensystem.io/nodes/2068/detail

2018-01-01 20:22:30GMT | 2018-01-02 12:04:18GMT | 2018-01-02 12:08:09GMT | 15:45:39 | zend

**Comment by ADumaine** [comment]
The phantom down times issues were addressed with server updates the week of Feb 5th.  Nodes may still be getting short Downtimes created which are legitimate disconnects, but there should not be any of the longer hour or more ones.
