### ISSUE TITLE
Inexplicable downtime (up to 13 days)

### ISSUE THREAD

**Issue by bclermont** [ZencashOfficial/secnodetracker#34]
January 3, of my securenode suddenly reported 10-12 hours downtime.
every few hours, I manually check and everything was ok. no reports of failures in the previous 12 hours.
Something happened to NA server?

Or more inexplicable: a 13 days downtime... that is clearly invalid, because during those days, the registry report other up/down.

is it because SEA server had been back online?

I switched from SEA to NA 13 days ago, and old downtime in SEA was resolved yesterday?

that explains that all my nodes that connected to SEA got this weird downtime. but the only node that never connected to it didn't got it

[node 5197](https://ts1.na.zensystem.io/nodes/5197/detail)

downtime that appeared for no reason, ID `238586`:

```
2018-01-02 21:44:24GMT    2018-01-03 09:34:05GMT    2018-01-03 09:34:05GMT    11:49:41    sys
```

this is the 13 days downtime that is impossible, because it was reported down/up during those days. ID is `175702`

```
2017-12-20 00:46:29GMT    2017-12-20 00:48:01GMT    2018-01-02 12:08:08GMT    13d 11:21:39    sys
```

[node 5251](https://ts1.eu.zensystem.io/nodes/5251/detail)

downtime that appeared for no reason, ID is `238592`:

```
2018-01-02 12:48:27GMT    2018-01-03 09:34:07GMT    2018-01-03 09:34:07GMT    20:45:40    sys
```

[node 5281](https://ts1.na.zensystem.io/nodes/5281/detail)

downtime that appeared for no reason, ID is `238583`:

```
2018-01-02 18:58:25GMT    2018-01-03 09:34:04GMT    2018-01-03 09:34:04GMT    14:35:39    sys
```

[node 5284](https://ts1.na.zensystem.io/nodes/5284/detail)

downtime that appeared for no reason, ID is `238589`:

```
2018-01-02 18:58:22GMT    2018-01-03 09:34:07GMT    2018-01-03 09:34:07GMT    14:35:45    sys
```

here is a template to execute on your SQL server:

```
DELETE FROM downtime WHERE id IN (238586,175702,238592,238583,238589)
```

**Comment by ADumaine** [comment]
There were some connectivity with the servers today which resulted in some of the downtimes you posted.  It looks like you have an older one too.  I thought those were all caught.  I'll use the information you provided to help identify ones for others.  It may take a few days to get some time to sort them out.

**Comment by ADumaine** [comment]
Some of the data you provided was used to help figure out some of the issues causing the phantom 
Downtimes. There will be a form available soon in the new help desk system to claim payments that were missed.
