### ISSUE TITLE
ipv6 registration not working

### ISSUE THREAD

**Issue by brutuscat** [ZencashOfficial/secnodetracker#35]
When running the tracker, I selected the ipv6 only option and entered a domain that has a proper AAAA dsn record pointing to my server ipv6 address. 

But because the same computer runs another node over ipv4 I am getting the following message:

> Registration failed. IP Address already registered. 51.XXXXX

The "failing" zen node is configured as so (ips stripped) `zen-cli getnetworkinfo` :
```json
{
  "version": 2001051,
  "subversion": "/zen:2.0.10-1/",
  "protocolversion": 170002,
  "localservices": "0000000000000001",
  "timeoffset": 0,
  "connections": 8,
  "tls_cert_verified": false,
  "networks": [
    {
      "name": "ipv4",
      "limited": true,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00000100,
  "localaddresses": [
    {
      "address": "2001:XXXXXXXXXX",
      "port": 9034,
      "score": 1
    }
  ],
  "warnings": "WARNING: check your network connection, 0 blocks received in the last 4 hours (96 expected)"
}
```

Anything else I should provide?

I was expecting the tracker to register the "node" even if it has the same ipv4 address, since they have different ipv6 addresses or just one is ipv4 only and the other one ipv6 only.

**Comment by brutuscat** [comment]
After "forcing" it to use ipv6 using the [helper script](https://github.com/ZencashOfficial/secnode_helper_scripts) I now get the "opposite" behavior, where the second tracker complains that the ipv6 address is now "already registered".

This is clearly a bug. I'll take a look at the source and try to submit a PR.

**Comment by asbachb** [comment]
@brutuscat you can use dev2 branch. I implemented already an workaround: https://github.com/ZencashOfficial/secnodetracker/pull/31

**Comment by brutuscat** [comment]
@asbachb yes thank you! I did and it worked, BUT now the node that goes over ipv6 is not listed in the website (even after I saw the "welcome you registered!" message...)

Ideas?

**Comment by asbachb** [comment]
@brutuscat you should join discord to dicsuss this issue if not yet already resolved. (If solved I'd suggest to close the ticket)

**Comment by brutuscat** [comment]
@asbachb not longer a problem. thx!
