### ISSUE TITLE
Use ZEN_HOME var in addition to or instead of searching for paths

### ISSUE THREAD

**Issue by JonDum** [ZencashOfficial/secnodetracker#4]
https://github.com/ZencashOfficial/secnodetracker/blob/f082bab3e2e599838624f15e50f82e7411b7d0bf/setup.js#L184-L186

Using environment variables is far more portable and allows admins greater flexibility. Should use ENV vars where possible e.g., if `ZEN_HOME` is defined use that to look for `ZEN_HOME/zen.conf`, etc. This makes it much easier when working in Docker containers too.

**Comment by ADumaine** [comment]
added to 0.1.0
