### ISSUE TITLE
Nodes failing challenges 24 hours after successful manual challenges sent

### ISSUE THREAD

**Issue by psyraxaus** [ZencashOfficial/secnodetracker#40]
secnodetracker version 0.2.0
Ubuntu Release:	17.10
Codename:	artful
node v9.1.0

I have had a number of nodes with a failed challenge timeout exception or previous challenge running exception, and tried this workaround:

Before running through this, I ensured there are are no open challenges in the wait state and I  restarted of the tracker, then used a manual-manual process of the following:

Obtained the node t-address using 
zen-cli listaddresses

 then either ran 
https://securenodes.your_region.zensystem.io/node_t_addres/node_id/send
 or 
https://securenodes2.your_region.zensystem.io/node_t_addres/node_id/send

depending on whether which servers I was connected to and which region.

24 hours later the automatic challenge sent from the server failed with the same challenge timeout exception.

Appeared to happen on all my nodes regardless of the region or server they were connected to.

I have re-run the above process at approximately 1800 AEDST 14 Jan, so I will keep an eye at around the same time on Jan 15 and update this issue with further detail.

**Comment by 3rdIteration** [comment]
I am seeing the same behaviour. 

Ubuntu 16.04, Node 8.9, tracker 0.2.0

Also getting periodic errors that the challenge balance is too low, though I checked it and it is fine.

**Comment by Tantrum403** [comment]
I have the same issue...

**Comment by xavren** [comment]
Same for me 

docker node:8, tracker 0.2.0

**Comment by asbachb** [comment]
It's not useful that everybody is posting "me too". A +1 to bug report should be enough.

**Comment by psyraxaus** [comment]
My 0.2.0 version trackers all experienced the same issue 24 hours + 6 mins from the previous successful challenge.

I did notice on the console for the tracker when a challenge was sent to the node, an Operation ID was reported but that was it.  The shielded transaction was still running but not output in the tracker console was present. 

Even though the shielded transaction completed, an exceed reply time out exception still resulted on the tracker website.

**Comment by ADumaine** [comment]
Version 0.2.1 fixes the challenge still running issue.

**Comment by psyraxaus** [comment]
Thank you @ADumaine, I will close this issue now
