### ISSUE TITLE
switching from testnet yields registration error

### ISSUE THREAD

**Issue by blbradley** [ZencashOfficial/secnodetracker#48]
Looks like this:

```
2018-02-21 15:48:46 GMT -- Could not find a registration. Not authenticated.
```

I had to delete my secnodetracker repo, reclone, and start the setup process again. Everything worked fine after that.

**Comment by ADumaine** [comment]
When switching from testnet to mainnet the following general steps can be followed:
 - stop the tracker app  ('pm2 stop 0' if running pm2)
 - stop zend  using 'zen-cli stop'
 - change zen.conf by commenting out '#testnet=1'  or removing it. Update the rpc user and password if needed to a strong password.
 - start zend and wait for it to sync the mainnet blockchain
 - delete the contents of secnodetracker/config folder
 - run 'node setup' and enter mainnet info at the prompts 
 - restart the tracker using pm2 once chain is synced

Also be sure port 9033 is open in the firewall for peer connections
