### ISSUE TITLE
How to reinstall the securenode

### ISSUE THREAD

**Issue by helsins** [ZencashOfficial/secnodetracker#49]
My rental VPS operation system is out of order, so I reset the system, and reinstall the securenode again. But after installing it, after executing "node app.js", the system prompts "Registration failed. IP Address already registered".

How can I get back to the security node?

I have recorded the Zaddr and password of the old securenode.

**Comment by ADumaine** [comment]
If you have a backup of the wallet.dat you should replace the new one with the old one.

If not, you will need the old stake address and the node id.  Create a file called nodeid in the secnodetracker/config folder and enter the nodeid in it.  Then restart the tracker.

**Comment by helsins** [comment]
Thank you very much @ADumaine, Can you take a look at the attachment and confirm the two questions?
1, Is 192.155.81.134 "the old stake address" ？
2, what is the "node id"? zen.helsin.xyz?
thank you again:)
![oldznodeinfo](https://user-images.githubusercontent.com/34838187/36584418-90fa36be-18b4-11e8-8299-738b4879c864.JPG)

**Comment by helsins** [comment]
an other question, what format should the nodeid file be，thanks

**Comment by helsins** [comment]
I created a file called “nodeid”, the content is as follows:

“address”:"192.155.81.134",
"nodeid":"zen.helsin.xyz"
#end of file
then i restart the tracker with "node app.js", the prompt are an follows:

2018-02-23 08:31:45 GMT -- Stats received by ts2.na
2018-02-23 08:31:45 GMT -- Incorrect nodeid "address":"192.155.81.134",
"nodeid":"zen.helsin.xyz" sent with config update. Please check config

**Comment by ADumaine** [comment]
The node id is not the ip address.  It can be found in any of the url when viewing the node details page or on the node challenge results page of the web site.

**Comment by KaMaToZzz** [comment]
Same:
nodetracker/config/nodeid:
"address":"88760",
"nodeid":"zzze.in-crimea.com"
#end of file

What is wrong? Have error:
Registration failed. IP Address already registered
