### ISSUE TITLE
Cert check: valid=false.  socket hang up

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [ZencashOfficial/secnodetracker#54]
The tracker reports socket hang up and cant check the cert.
Cert is failed according to zen-cli getnetworkinfo. 
{
  "version": 2001051,
  "subversion": "/zen:2.0.10-1/",
  "protocolversion": 170002,
  "localservices": "0000000000000001",
  "timeoffset": 0,
  "connections": 12,
  "tls_cert_verified": true,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00000100,
  "localaddresses": [
  ],
  "warnings": ""
}

First time this happen i restarted zend and this resolved the issue. 

Any help would be great.

Many Thanks

**Comment by ADumaine** [comment]
Do you have maxconnections = 12 in your zen.conf?

**Comment by jamiejacksoncumbria** [comment]
Well Done thanks mate that did the trick. I missed that one thanks.

**Comment by ADumaine** [comment]
I just wanted to confirm it was set.  There should be no need to remove it.

Removing that now is just a workaround until the next server update, which is being deployed today.  It will check for the hang message and fall over to peer counts.  In final testing now.

**Comment by jamiejacksoncumbria** [comment]
Thanks Ill look out for the update.

Thanks
