### ISSUE TITLE
Cert check fails when zen-cli says tls cert is verified

### ISSUE THREAD

**Issue by chrisblizz** [ZencashOfficial/secnodetracker#56]
Hey,

I am having trouble passing the cert check.

secnodetracker gives me
`Cert check: valid=false.  No peers found yet with secure connections to this node.`

when zen-cli states:
`"tls_cert_verified": true,`

Any ideas?

**Comment by ADumaine** [comment]
The tracking server attempt to connect to a node on port 9033 to verify TLS.   If it can not connect it will check other nodes that are connected to your node to see if the established a connection.

Make sure port 9033 is open in your firewall.
You can also open a ticket at support.zencash.com to get some more help.

**Comment by chrisblizz** [comment]
That's it. Could have gotten it by myself. Anyways, thanks a lot!
