### ISSUE TITLE
Memory leak!

### ISSUE THREAD

**Issue by GroovyGrovesy** [ZencashOfficial/secnodetracker#6]
I have a 2GB Linode with 4GB of swap and I kept getting exceptions so when I checked and zend was using a massive amount of memory (RAM & Swap) whilst it was just sitting there idle.

![image](https://user-images.githubusercontent.com/7847340/32546709-e4b17f88-c477-11e7-956f-eb3bef50f9b0.png)

I restarted zend but when it came back up it was using the same amount of memory.  I then stopped both zend and the tracker then started them in the same order and now the memory useage is back to an acceptable level

![image](https://user-images.githubusercontent.com/7847340/32547021-c4113d6c-c478-11e7-9a9c-aac868c2fd82.png)

**Comment by GroovyGrovesy** [comment]
latest with swap

![image](https://user-images.githubusercontent.com/7847340/32546985-af7e56e6-c478-11e7-8d4a-daafeebe7d22.png)

**Comment by GroovyGrovesy** [comment]
So when the next challenge was run the Memory usage jumped back up as expected but stayed there when the challenge finished.
![image](https://user-images.githubusercontent.com/7847340/32556173-9eeccc7c-c496-11e7-993a-6ffd05d4c05b.png)

**Comment by ADumaine** [comment]
The tracking app has no control over how zen works.
Please move this to https://github.com/ZencashOfficial/zen/issues.
