### ISSUE TITLE
rpc config parsing

### ISSUE THREAD

**Issue by bumbar1** [ZencashOfficial/secnodetracker#60]
Config values (namely `rpchost` and `rpcport`) are not (whitespace) cleaned up properly, which results in unhelpful errors.

If `rpcport` contains new line, tracker will fail to start with `Zend error: connect ECONNREFUSED ip:80`. Lost a few hours trying to find where it's getting port 80, even after dozen checks to see that rpc ports are the same in both (zend and tracker) configs.

Same thing for `rpchost`, fails to connect.

Came across this problem when I was manually editing tracker config to get it working in docker. I've used vim and nano, which both append a newline at the end, [as per posix standard](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

Also not sure why a simple json config couldn't have been used.

**Comment by PeaStew** [comment]
Most of us use vim or nano and do not have this problem. Agree on the json config though.

**Comment by ADumaine** [comment]
The config files were never intended to be edited directly.  
If you need to make a change you can try just overwriting with echo.

Example for fqdn:
echo my.node.com > ./config/fqdn

**Comment by PeaStew** [comment]
actually printf or echo -n is necessary, echo by itself will also add a newline

**Comment by ADumaine** [comment]
Thank you for correcting that PeaStew!

**Comment by bumbar1** [comment]
Overwriting with echo is editing in a way.

It's a simple fix, calling .trim, in [SecNodeTracker.js#L12](https://github.com/ZencashOfficial/secnodetracker/blob/1f5970620f5d7b9e20e140fa7203b3ce328f979c/SecNodeTracker.js#L12) and [SecNodeTracker.js#L13](https://github.com/ZencashOfficial/secnodetracker/blob/1f5970620f5d7b9e20e140fa7203b3ce328f979c/SecNodeTracker.js#L13), like it was for [stake address](https://github.com/ZencashOfficial/secnodetracker/blob/master/app.js#L58).
